name: DB Migrations

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: List migration files
        run: |
          echo "Migration files:" 
          ls -1 supabase/*.sql

      - name: Apply migrations
        run: |
          set -euo pipefail
          if [ -z "${DATABASE_URL:-}" ]; then
            echo "DATABASE_URL is not set. Aborting." >&2
            exit 1
          fi
          for f in supabase/*.sql; do
            echo "Applying $f"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
